apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app.provider.secret
spec:
  provider: azure
  secretObjects:
    - secretName: db
      type: Opaque
      data:
        - objectName: uvr-db-password
          key: password
  parameters:
    tenantId: {{ .Values.azureTenant }}
    keyvaultName: {{ .Values.keyvault.name }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.user }}
    objects: |
      array:
        - |
          objectName: uvr-db-password
          objectType: secret
