replicaCount: 1

namespace: uvr

azureTenant: 00000000-0000-0000-0000-000000000000

image:
  repository: 000000000000000000000
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: { }
  name: "zum-uvr"

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

db:
  username: "uvr"

kafka:
  ssl:
    truststore:
      location: "/jks/kafkaTrustStore.p12"
    keystore:
      location: "/jks/kafkaKeyStore.jks"
